### ISSUE TITLE
`Keybow2040` device won't compile, gives unsatisfied trait bound for `embedded_hal_async::i2c::I2c`

### ISSUE THREAD

**Issue by trepidacious** [Univa/rumcake#2]
## Description of the issue

If you use the `Keybow2040` device, it fails on compilation with:

```text
note: the following trait bounds were not satisfied:
      `<I2C as embedded_hal_async::i2c::ErrorType>::Error = _`
      `I2C: I2c`
```

I've submitted a [PR to address this](https://github.com/Univa/is31fl3731/pull/1)

## Hardware

I'm actually using `Univa/is31fl3731` directly from an RP2040 board (Keybow 2040) - at the moment I'm just doing some messing around to get a basic keyboard running so I'm not using rumcake itself, but I'd like to try out using more of it as I go.

## Version of `rumcake` used

I'm using the same is31fl3731 crate as current `rumcake` main, with:

```toml
is31fl3731 = { git = "https://github.com/Univa/is31fl3731", features = ["async", "keybow_2040"] }
```

## Minimum Reproducible Example

You just need to set up a matrix using `Keybow2040` to see the error, my code on RP2040 is as follows:

```rust
    let p = embassy_rp::init(Default::default());

    let sda = p.PIN_4;
    let scl = p.PIN_5;

    info!("set up i2c ");
    let i2c = i2c::I2c::new_async(p.I2C0, scl, sda, Irqs, i2c::Config::default());

    // Create LED matrix driver
    let mut matrix = Keybow2040::configure(i2c);
```

## How to Reproduce

1. Set up a matrix using `Keybow2040`
4. Run `cargo build`

## Expected Behaviour

Code compiles.

**Comment by Univa** [comment]
Closing this issue since it seems like more of an issue with the `is31fl3731` crate rather than the `rumcake` crate. I have added comments to your PR in that repo.

**Comment by trepidacious** [comment]
Thanks - I've updated the PR. I couldn't see issues on the `is31fl3731` repo so I thought I'd add it here - might be disabled in settings?

**Comment by Univa** [comment]
> Thanks - I've updated the PR. I couldn't see issues on the `is31fl3731` repo so I thought I'd add it here - might be disabled in settings?

My bad, didn't realize it was off. Should be fixed now.
