### ISSUE TITLE
Feature: Double-Tap reset button to Enter bootloader

### ISSUE THREAD

**Issue by zUnixorn** [Univa/rumcake#5]
### Type of Feature Request

- [ ] Enhancement to an existing `rumcake` feature
- [X] New feature unrelated to existing `rumcake` features
- [ ] New driver for existing `rumcake` features
- [ ] Support for a new MCU

### Description

Hello, first of all, thank you for this amazing project. Now that there is RP2040 support, I really want to use this firmware for my Corne, instead of QMK.

In QMK there is an option to enter the UF2 Bootloader with a [double-tap of the reset button](https://github.com/qmk/qmk_firmware/blob/master/docs/platformdev_rp2040.md#double-tap-reset-boot-loader-entry-iddouble-tap). I use this feature, since my Corne PCB only exposes the reset button but not the boot button. 

The feature is already implemented in my fork ([here](https://github.com/zUnixorn/rumcake/tree/bootloader-double-tap-reset)) and I could open a pull request if you are interested. 

In my implementation, the feature is not exclusive to the RP2040 but can only really be used with it, since the other MCUs do not currently have an implemented `jump_to_bootloader()` function. I also am not sure what the best way is, to configure the timeout time, currently it can be change via an environment variable at compile-time

**Comment by Univa** [comment]
Feel free to open a PR, I can take a deeper look at some point. For the timeout configuration, I would just add an optional field for the `#[keyboard]` macro (in the `KeyboardSettings` struct), then pass it as an argument to your bootloader magic task. I can provide more guidance in the PR.

**Comment by zUnixorn** [comment]
Thanks for the feedback. I opened a pull-request for this (#6) now
